<a href="https://colab.research.google.com/github/berux-24/VU_Amuko-Brenda_Programming_Practice/blob/main/practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import files

uploaded = files.upload()

import pandas as pd
import io

file_name = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[file_name]))

df.head()

Saving Student Study Habits and Academic Performance Questionnaire.csv to Student Study Habits and Academic Performance Questionnaire (1).csv

,Timestamp,1. Level of study,2. Year of study,"3. On average, how many hours do you study outside class per day?",4. How many days per week do you normally study outside class?,5. Approximately how many hours do you study outside class in a typical week?,6. What was your overall percentage in your most recent completed examination or assessment?,7. Which category best describes your most recent academic score?,8. How consistent is your study schedule?,9. Do you normally complete the study sessions you plan?
0,2026/10/06 8:20:30 AM GMT+3,Bachelor's Degree,Year 1,2.0,3,7.0,60,60–69%,Sometimes consistent,Yes
1,2026/10/06 8:25:03 AM GMT+3,Diploma,Year 1,5.0,5,8.0,70,70–79%,Often consistent,Yes
2,2026/10/06 8:26:40 AM GMT+3,Certificate,Year 2,5.0,6,8.0,65,60–69%,Always consistent,Yes
3,2026/10/06 8:28:31 AM GMT+3,Bachelor's Degree,Year 3,3.0,3,6.0,80,80–100%,Often consistent,Sometimes
4,2026/10/06 8:43:07 AM GMT+3,Diploma,Year 2,2.0,6,12.0,89,80–100%,Always consistent,Yes

In [4]:
print(df.columns)
print(df.shape)
df.info()

Index(['Timestamp', '1. Level of study', '2. Year of study',
       '3. On average, how many hours do you study outside class per day?',
       '4. How many days per week do you normally study outside class?',
       '5. Approximately how many hours do you study outside class in a typical week?',
       '6. What was your overall percentage in your most recent completed examination or assessment?',
       '7. Which category best describes your most recent academic score?',
       '8. How consistent is your study schedule?',
       '9. Do you normally complete the study sessions you plan?'],
      dtype='object')
(32, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 10 columns):
 #   Column                                                                                        Non-Null Count  Dtype
---  ------                                                                                        --------------  -----
 0   Timestamp                                                                                     32 non-null     object
 1   1. Level of study                                                                             32 non-null     object
 2   2. Year of study                                                                              32 non-null     object
 3   3. On average, how many hours do you study outside class per day?                             32 non-null     float64
 4   4. How many days per week do you normally study outside class?                                32 non-null     int64
 5   5. Approximately how many hours do you study outside class in a typical week?                 32 non-null     float64
 6   6. What was your overall percentage in your most recent completed examination or assessment?  32 non-null     int64
 7   7. Which category best describes your most recent academic score?                             32 non-null     object
 8   8. How consistent is your study schedule?                                                     32 non-null     object
 9   9. Do you normally complete the study sessions you plan?                                      32 non-null     object
dtypes: float64(2), int64(2), object(6)
memory usage: 2.6+ KB

DATA CLEANING AND RENAMING COLUMNS

In [10]:
df = df.rename(columns = {'1. Level of study':'level','2. Year of study':'year','3. On average,how many hours do you study outside class per day?':'study_hours'})

print(df.columns)

Index(['timestamp', 'level', 'year', 'study_hours_per_day',
       'study_hours_per_week', 'total_study_hours', 'percentage',
       'academic_score', 'consistency', 'complete_sessions'],
      dtype='object')

In [9]:
df.columns=[
    'timestamp',
    'level',
    'year',
    'study_hours_per_day',
    'study_hours_per_week',
    'total_study_hours',
    'percentage',
    'academic_score',
    'consistency',
    'complete_sessions'
]

print(df.columns)

Index(['timestamp', 'level', 'year', 'study_hours_per_day',
       'study_hours_per_week', 'total_study_hours', 'percentage',
       'academic_score', 'consistency', 'complete_sessions'],
      dtype='object')

In [11]:
print("---Unique Study Levels---")
print(df['level'].unique())

print("\n---Student Count by Year---")
print(df['year'].value_counts())

---Unique Study Levels---
["Bachelor's Degree" 'Diploma' 'Certificate']

---Student Count by Year---
year
Year 1     16
Year 2     10
Year 3      5
Year 4+     1
Name: count, dtype: int64

In [ ]:
# data filtering
new_df = df[ df['column_name'] == 'specific_value']

In [13]:
# filtering text(categorical data)
undergrads = df[ df['level'] == 'Undergraduate']
undergrads.head()

Empty DataFrame
Columns: [timestamp, level, year, study_hours_per_day, study_hours_per_week, total_study_hours, percentage, academic_score, consistency, complete_sessions]
Index: []

In [16]:
# filtering numbers
hard_workers = df[ df['study_hours_per_day']>4]
print(hard_workers.shape)

(4, 10)

In [20]:
# filtering with multiple conditions(AND/OR)
advanced_filter = df[ (df['study_hours_per_day']>4) & (df['year'] =='Year 1')]
print(advanced_filter.shape)

advanced_filter.head()

(1, 10)

,timestamp,level,year,study_hours_per_day,study_hours_per_week,total_study_hours,percentage,academic_score,consistency,complete_sessions
1,2026/10/06 8:25:03 AM GMT+3,Diploma,Year 1,5.0,5,8.0,70,70–79%,Often consistent,Yes

In [ ]:
# CATEGORICAL ENCODING(turning words into numbers)
#ai are giant mathematical calculators and cant process text,you must convert strings into numbers.

In [23]:
#create mapping dictionaries
Level_map = {'Certificate':0, 'Diploma':1, "Bachelor's Degree":2}
year_map =  {'Year 1':1,'Year 2':2,'Year 3':3,'Year 4+':4,}

df['level_encoded'] = df['level'].map(Level_map)
df['year_encoded'] = df['year'].map(year_map)

df[['level', 'level_encoded', 'year', 'year_encoded']].head()

               level  level_encoded    year  year_encoded
0  Bachelor's Degree              2  Year 1             1
1            Diploma              1  Year 1             1
2        Certificate              0  Year 2             2
3  Bachelor's Degree              2  Year 3             3
4            Diploma              1  Year 2             2

In [ ]:
# FEATURE SPLITTING(X and y)
#in machine learning,always separate datasets into 2 distinct parts
#X(Features): the inputs or clues
#y(Target): the single outcome variable you want the ai to learn to predict

In [24]:
y = df['academic_score']
X = df.drop(columns=['timestamp','level','year','academic_score'])

print("---splitting complete")
print("---Features Matrix (X) shape:", X.shape)
print("Target vector (y) shape:", y.shape)

---splitting complete
---Features Matrix (X) shape: (32, 8)
Target vector (y) shape: (32,)

In [27]:
# machine learning code

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

y = df['percentage']
X = df[['level_encoded','year_encoded','study_hours_per_day','study_hours_per_week']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("---Ai Model Training Complete---")
print("Model R**2 Score (Accuracy):", r2_score(y_test, y_pred))
print("Mean Squared Error (MSE):", mean_squared_error(y_test, y_pred))

---Ai Model Training Complete---
Model R**2 Score (Accuracy): -8.837691717977684
Mean Squared Error (MSE): 2008.0937257798525